# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  db:
    image: mysql:8
    container_name: sisurabi_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sisurabi
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  api:
    build: ./server
    container_name: sisurabi_be
    working_dir: /app
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db
    command: npm run dev

  frontend:
    build: .
    container_name: sisurabi_fe
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api
    command: npm run dev -- --host 0.0.0.0

volumes:
  db_data:

