-- AlterTable
ALTER TABLE `LaporanSuvenir` ADD COLUMN `approvedAt` DATETIME(3) NULL,
    ADD COLUMN `approvedBy` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'TERLAMBAT') NOT NULL DEFAULT 'PENDING';
